sudo: required

services:
  - docker

before_install:
  - docker build -t browserless/base:latest base
  - docker build -t browserless/chrome:latest .
  - docker build --build-arg "USE_CHROME_STABLE=true" -t browserless/chrome:stable .

script:
  - docker run -it -e CI=true --entrypoint ./node_modules/.bin/jest browserless/chrome:latest --runInBand --bail --forceExit
  - docker run -it -e CI=true --entrypoint ./node_modules/.bin/jest browserless/chrome:stable --runInBand --bail --forceExit
