name: Publish Latest Docker Images to GitHub Container Registry

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  push_to_registry:
    name: Push multi-platform docker images to ghcr.io
    runs-on: ubuntu-24.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish the latest Base image
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          file: ./docker/base/Dockerfile
          tags: |
            ghcr.io/divmode/browserless-base:latest
          context: .
          push: true
          platforms: |
            linux/amd64
            linux/arm64

      - name: Publish the latest Chromium image
        uses: docker/build-push-action@v5
        with:
          build-args: |
            VERSION=latest
          builder: ${{ steps.buildx.outputs.name }}
          file: ./docker/chromium/Dockerfile
          tags: |
            ghcr.io/divmode/browserless-chromium:latest
          context: .
          push: true
          platforms: |
            linux/amd64
            linux/arm64

      - name: Publish the latest Chrome image
        uses: docker/build-push-action@v5
        with:
          build-args: |
            VERSION=latest
          builder: ${{ steps.buildx.outputs.name }}
          file: ./docker/chrome/Dockerfile
          tags: |
            ghcr.io/divmode/browserless-chrome:latest
          context: .
          push: true
          platforms: |
            linux/amd64

      - name: Publish the latest Edge image
        uses: docker/build-push-action@v5
        with:
          build-args: |
            VERSION=latest
          builder: ${{ steps.buildx.outputs.name }}
          file: ./docker/edge/Dockerfile
          tags: |
            ghcr.io/divmode/browserless-edge:latest
          context: .
          push: true
          platforms: |
            linux/amd64

      - name: Publish the latest FireFox image
        uses: docker/build-push-action@v5
        with:
          build-args: |
            VERSION=latest
          builder: ${{ steps.buildx.outputs.name }}
          file: ./docker/firefox/Dockerfile
          tags: |
            ghcr.io/divmode/browserless-firefox:latest
          context: .
          push: true
          platforms: |
            linux/amd64
            linux/arm64

      - name: Publish the latest Webkit image
        uses: docker/build-push-action@v5
        with:
          build-args: |
            VERSION=latest
          builder: ${{ steps.buildx.outputs.name }}
          file: ./docker/webkit/Dockerfile
          tags: |
            ghcr.io/divmode/browserless-webkit:latest
          context: .
          push: true
          platforms: |
            linux/amd64
            linux/arm64

      - name: Publish the latest Multi image
        uses: docker/build-push-action@v5
        with:
          build-args: |
            VERSION=latest
          builder: ${{ steps.buildx.outputs.name }}
          file: ./docker/multi/Dockerfile
          tags: |
            ghcr.io/divmode/browserless-multi:latest
          context: .
          push: true
          platforms: |
            linux/amd64
            linux/arm64
